### PR TITLE
hostname command fixed

### PR DESCRIPTION
**Pull request by Moork0**
--all-ip-addresses has been deprecated

### CODE REVIEW

**Review by Varbaek — CHANGES_REQUESTED** [review]
hostname -i returns 127.0.1.1 / localhost on my system. 
hostname -I returns the IP address for eth0 / ens33.

**Comment by Varbaek** [comment]
Which Linux distribution and version are you using?

**Comment by Moork0** [comment]
I use arch linux.
yes that was my mistake with that '-i' argument.
i found another way to get the network card(s) IP(s).
executing this :
ip addr | grep -o "inet [1-9.\/]* " | tr -d 'inet '
thanks.

**Comment by Varbaek** [comment]
What happens if you change --all-ip-addresses to -I? Does it present the IP addresses correctly? 
Thanks for the other command, that should be more stable on the long run perhaps, despite being a lot more complex.

**Comment by Moork0** [comment]
The -I option doesn't exist.
Any time ! I like your projects. 
And.. I have some questions..  how can i ask them ? with email ?

**Comment by Varbaek** [comment]
Ah okay, I thought it was only the long option that had been deprecated.
Sure, xsser@varbits.net

Your pull request is using commands which is deprecated. 
(https://docs.python.org/2/library/commands.html)

Thanks for both of the pull requests. I'll look into changing it to the command line you provided.

**Comment by Moork0** [comment]
I wanted to use getoutput from subprocess but that was for python3. so i didn't find any thing else except commands.
Thanks to you <3

**Pull request closed without merging**
